version: '3.9'

services:
  db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 5
  backend:
    image: danteonline/webpython-backend
    build:
      context: .
    expose:
      - 8080
    environment:
      PGDB: "${POSTGRES_DB}"
      PGUSER: "${POSTGRES_USER}"
      PGPASSWORD: "${POSTGRES_PASSWORD}"
    command: bash -c "
      python manage.py migrate --settings=zoo.prod_settings
      && gunicorn zoo.wsgi -b 0.0.0.0:8080
      "
    depends_on:
      db:
        condition: service_healthy
  nginx:
    image: danteonline/webpython-nginx
    build: ./nginx
    ports:
      - 8000:80
    depends_on:
      - backend
  frontend:
      image: danteonline/webpython-frontend
      build:
        context: ./frontend
      ports:
        - 3000:80